name: Docker Image CI 

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
env:
  IMAGE: mluvii/api-gateway-heimstaden-sessionview
  VERSION: 1.0.0.${{ github.run_number }}
  NAME: api-gateway-heimstaden-sessionview-production

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GIT_TOKEN }}
          submodules: true
      - name: Log in to Docker Hub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: $env.IMAGE
          file: ./Dockerfile
          
      - name: Build and push Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          file: ./Dockerfile
          context: ./
          push: true
          tags: ${{ env.IMAGE }}:${{ env.VERSION }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: SSH Key
        env:
          SSH_SECRET: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
            echo "$SSH_SECRET" > key; chmod 400 ./key

      - name: Play Ansible Playbook
        uses: arillso/action.playbook@master
        with:
          playbook: DeployAnsible/main.yml
          inventory: DeployAnsible/hosts.yml
          extra_vars: 'IMAGE=${{ env.IMAGE }}:${{ env.VERSION }} MLUVII_CLIENT_ID=${{ env.MLUVII_CLIENT_ID }} MLUVII_CLIENT_SECRET=${{ env.MLUVII_CLIENT_SECRET }} NAME=${{ env.NAME }}'
        env:
          ANSIBLE_HOST_KEY_CHECKING: False
          ansible_ssh_private_key_file: './key'
          ansible_user: 'drosko' 
          MLUVII_CLIENT_ID: '${{ secrets.MLUVII_CLIENT_ID }}'
          MLUVII_CLIENT_SECRET: '${{ secrets.MLUVII_CLIENT_SECRET }}'
          